# Generated by Django 3.2.16 on 2023-01-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230127_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='products',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(to='product.Cart'),
        ),
    ]
