# Generated by Django 3.2.16 on 2023-02-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230202_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
