# Generated by Django 3.2.16 on 2023-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
