# Generated by Django 3.2.16 on 2023-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(null=True),
        ),
    ]
