# Generated by Django 3.2.16 on 2023-02-24 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20230223_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
