# Generated by Django 3.2.16 on 2023-02-24 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_orderproduct_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
